In [1]:
#Import required python modules
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.naive_bayes import GaussianNB

In [23]:
#load data from file
#data = np.genfromtxt('iris.csv', delimiter=',',skip_header=True)
#trainingDataCount = 80

data = np.genfromtxt('iris_multiclass.csv', delimiter=',',skip_header=True)
trainingDataCount = 120

input_columns = [0,1,2,3]
output_column = [5]


#Distribute data into train and test sets
X_train = data[:trainingDataCount,input_columns]
Y_train = data[:trainingDataCount,output_column]

X_test = data[trainingDataCount:,input_columns]
Y_test = data[trainingDataCount:,output_column]


In [24]:
#Flatten the 2D column vector into 1D array
Y_train = Y_train.ravel()
Y_test = Y_test.ravel()

In [25]:
#Generate the model
model = GaussianNB()
model.fit(X_train, Y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [27]:
#Check for an example scenario
example_input = [[1,1,3.5,1]]
#example_input = [[5.2,2.9]]
print(model.predict(example_input))
print(model.predict_proba(example_input))

[3.]
[[4.52312536e-45 3.23533258e-03 9.96764667e-01]]


In [28]:
#Calculate the performance of the model using model defined score function
print(model.score(X_test,Y_test))

0.9


In [29]:
#Calculate the performance of the model using model defined predict function
resultMatrix = model.predict(X_test).reshape(-1,1)
Y_test = Y_test.reshape(-1,1)
correctCount = np.sum((resultMatrix==Y_test).astype(int))
totalCount = len(X_test)
print("Total Correct Count: ",correctCount," Total Wrong Count: ",totalCount-correctCount," Accuracy: ",(correctCount*100)/(totalCount))

Total Correct Count:  27  Total Wrong Count:  3  Accuracy:  90.0


In [30]:
print("Number of training samples observed in each class: ", model.class_count_)
print("Prior probability of each class: ",model.class_prior_)
print("Class labels in the training examples: ", model.classes_)
print("Mean of each feature per class: ",model.theta_)
print("Variance of each feature per class: ",  model.sigma_)

Number of training samples observed in each class:  [45. 45. 30.]
Prior probability of each class:  [0.375 0.375 0.25 ]
Class labels in the training examples:  [1. 2. 3.]
Mean of each feature per class:  [[5.01111111 3.42       1.46444444 0.24666667]
 [5.87777778 2.75333333 4.22888889 1.31333333]
 [6.58333333 2.93333333 5.60333333 2.00666667]]
Variance of each feature per class:  [[0.12854321 0.14782223 0.03206914 0.01226667]
 [0.22483951 0.09137778 0.22072099 0.04026667]
 [0.45872223 0.10822223 0.37965556 0.06328889]]
